version: '3.8'

services:
  oauth_relay_service:
    build: .
    ports:
      - "8080:8080" # HTTP/REST
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    volumes:
      - ./data:/usr/src/oauth_relay_service/tokens.sqlite.db
